---
- name: Install docker engine [CE]
  hosts: nodes
  become: yes
  vars_files:
    - ./external_vars.yml

  tasks:    
    - name: Uninstall older versions of Docker [if exist]
      apt:
        name: "{{ item }}"
        state: absent
        with_items:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc

    - name: update apt
      apt:
        update_cache: yes

     - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
        with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add docker’s official GPG key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution }}"" stable
        state: present
        filename: docker_registry

    - name: Install docker engine [CE]
      apt:
        name: "{{ item }}"
        state: latest
        with_items:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        notify:
        - Restart docker

    - name: Add ubuntu user to the docker group
      user:
        ### Contuniue from here step #3 in install docker engin

    handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted
      

    