---
- name: Setup ansible on remote EC2 server
  hosts: servers
  become: yes
  vars_files:
    - ./external_vars.yml

  
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: latest

    - name: Add repository ppa:ansible/ansible
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
        filename: ppa-ansible
    
    - name: Install ansible
      apt:
        name: ansible
        state: latest

    - name: Copy private key to remote EC2 server
      copy:
        src: "{{ ssh_key }}"
        dest: /home/ubuntu/.ssh
        owner: ubuntu
        group: ubuntu
        mode: '0600'

      



      
