---
- name: Setup ansible on remote EC2 server
  hosts: servers
  become: yes
  vars_files:
    - ./external_vars.yml

  # ansible servers -i hosts.ini -m apt -a "update-cache=yes" --become
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: latest

    - name: Add repository ppa:ansible/ansible
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
        filename: ppa-ansible
    
    - name: Install ansible
      apt:
        name: ansible
        state: latest

    - name: Copy private key to remote EC2 server
      copy:
        src: "{{ ssh_key }}"
        dest: /home/ubuntu/.ssh
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    
    - name: Configure ssh
      template:
        src: ./ssh_conf.j2
        dest: /home/ubuntu/.ssh/config
        owner: ubuntu
        group: ubuntu
        backup: yes

    - name: Copy file with owner and permissions
      copy:
        src: "{{ homework_dir }}"
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Install python-pip
      apt:
        name: python-pip # We install python-pip and not python3-pip because the "default" python on this AMI is 2.7.17
        state: latest

    - name: Install boto3 & botocore
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - boto3
        - botocore


      



      
